# Generated by Django 6.0.6 on 2026-06-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_sms_delete_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sms',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='sms',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sms',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
